version: "3.9"

networks:
  internal_nw:
    name: internal_nw
    driver: bridge

services:
  app:
    build:
      context: ../.
      dockerfile: dev_setup/Dockerfile
    container_name: trading-api
    ports:
      - "8000:8000"
    networks:
      - internal_nw
    env_file:
      - ../.env
    depends_on:
      database:
        condition: service_healthy
      broker:
        condition: service_healthy

  database:
    container_name: database-node
    image: cockroachdb/cockroach:v22.2.0
    command: start-single-node --insecure --http-addr 0.0.0.0
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      - internal_nw
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  broker:
    image: rabbitmq:3.8-management
    container_name: rabbitmq-node
    hostname: broker
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./config/test_setup.sh:/dev/test_setup.sh"
      - "./config/definitions.json:/etc/rabbitmq/definitions.json"
      - "./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_NODE_IP_ADDRESS=0.0.0.0
      - NODE_IP_ADDRESS=0.0.0.0
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit loopback_users "none"
    command: >
      sh -c "rabbitmq-server"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal_nw
    depends_on:
      database:
        condition: service_healthy  

  message_consumer:
    build:
      context: ../.
      dockerfile: dev_setup/Dockerfile
    container_name: rabbitmq-consumer
    command: python app/event_subscriber/message_consumer.py
    networks:
      - internal_nw
    env_file:
      - ../.env
    depends_on:
      broker:
        condition: service_healthy

  celery_worker:
    build:
      context: ../.
      dockerfile: dev_setup/Dockerfile
    container_name: celery-worker
    command: celery -A app.worker.celery_app worker --loglevel=info
    networks:
      - internal_nw
    env_file:
      - ../.env
    depends_on:
      database:
        condition: service_healthy
      broker:
        condition: service_healthy

  celery_beat:
    build:
      context: ../.
      dockerfile: dev_setup/Dockerfile
    container_name: celery-beat
    command: celery -A app.worker.celery_app beat --loglevel=info
    networks:
      - internal_nw
    env_file:
      - ../.env
    depends_on:
      database:
        condition: service_healthy
      broker:
        condition: service_healthy
