version: "3.9"

networks:
  internal_nw:
    name: internal_nw
    driver: bridge

services:
  app:
    build:
      context: ../.
      dockerfile: dev_setup/Dockerfile
    container_name: trading-api
    ports:
      - "8000:8000"
    networks:
      - internal_nw
    env_file:
      - ../.env
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database-node
    image: cockroachdb/cockroach:v22.2.0
    command: start-single-node --insecure --http-addr 0.0.0.0
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      - internal_nw
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  broker:
    image: rabbitmq:3.8-management
    container_name: rabbitmq-node
    hostname: broker
    ports:
      - 0.0.0.0:5672:5672
      - 0.0.0.0:15672:15672
    volumes:
      - "./config/test_setup.sh:/dev/test_setup.sh"
      - "./config/definitions.json:/etc/rabbitmq/definitions.json"
      - "./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_NODE_IP_ADDRESS=0.0.0.0
      - NODE_IP_ADDRESS=0.0.0.0
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit loopback_users "none"
    command: >
      sh -c "rabbitmq-server"
    networks:
      - internal_nw
    depends_on:
      - database
      - app

  publisher:
    build:
      context: ../.
      dockerfile: dev_setup/Dockerfile
    container_name: publisher-service
    command: python -m app.core.message_publisher
    networks:
      - internal_nw
    env_file:
      - ../.env
    environment:
      PYTHONPATH: /src
    depends_on:
      broker:
        condition: service_started
      database:
        condition: service_healthy

  consumer:
    build:
      context: ../.
      dockerfile: dev_setup/Dockerfile
    container_name: consumer-service
    command: python -m app.event_subscriber.message_consumer
    networks:
      - internal_nw
    env_file:
      - ../.env
    environment:
      PYTHONPATH: "${PYTHONPATH}:/src"
    depends_on:
      broker:
        condition: service_started
      database:
        condition: service_healthy
